# Generated by Django 4.2.4 on 2023-08-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zagadka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresc', models.CharField(max_length=50)),
                ('odpowiedz', models.CharField(max_length=50)),
                ('podp1', models.CharField(max_length=50)),
                ('podp2', models.CharField(max_length=50)),
            ],
        ),
    ]
