# Generated by Django 4.2.4 on 2023-08-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_plik_podp1_plik_podp2_plik_submit_delete_plik'),
    ]

    operations = [
        migrations.AddField(
            model_name='zagadka',
            name='grafika',
            field=models.FileField(default='none', upload_to='images/zagadki'),
        ),
        migrations.AddField(
            model_name='zagadka',
            name='klucz_wejsciowy',
            field=models.CharField(default='brak', max_length=50),
        ),
        migrations.AddField(
            model_name='zagadka',
            name='klucz_wynikowy',
            field=models.CharField(default='brak', max_length=50),
        ),
    ]
