# Generated by Django 4.2.4 on 2023-08-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_zagadka_grafika_zagadka_klucz_wejsciowy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plik_graf_tyt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dokument', models.FileField(upload_to='images/tytulowa')),
            ],
        ),
        migrations.CreateModel(
            name='Plik_rozpocznij',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dokument', models.FileField(upload_to='images/rozpocznij')),
            ],
        ),
    ]
