# Generated by Django 4.2.4 on 2023-10-10 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_napisy'),
    ]

    operations = [
        migrations.CreateModel(
            name='LosoweHasla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresc', models.CharField(max_length=200)),
            ],
        ),
    ]
