# Generated by Django 4.2.4 on 2023-10-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_losowehasla'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plik_odp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dokument', models.FileField(upload_to='images/odp')),
            ],
        ),
    ]
