# Generated by Django 4.2.4 on 2023-11-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_plik_odp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plik_submit_kod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dokument', models.FileField(upload_to='images/submit_kod')),
            ],
        ),
    ]
